version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dmtx"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wh3uk63epz22"
s3_prefix = "dmtx"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
